name: Deploy Infrastructure

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy (leave empty for all)'
        required: false
        type: string

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
  INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
  INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          
      - name: Configure kubectl
        run: |
          doctl auth init -t ${{ secrets.DIGITALOCEAN_TOKEN }}
          doctl kubernetes cluster kubeconfig save integra-k8s-cluster
          
      - name: Login to Pulumi
        run: pulumi login
        
      - name: Select production stack
        run: pulumi stack select production
        
      - name: Configure Pulumi
        run: |
          pulumi config set --secret digitalOceanToken ${{ secrets.DIGITALOCEAN_TOKEN }}
          
      - name: Preview changes
        run: pulumi preview
        
      - name: Deploy infrastructure
        run: pulumi up --yes
        
      - name: Export stack outputs
        run: pulumi stack output --json > outputs.json
        
      - name: Upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: stack-outputs
          path: outputs.json